# ansible-rke2-rhel9/group_vars/all.yml

# IP หรือ DNS ของเครื่อง Control Plane แรก หรือ Load Balancer
# Ansible จะใช้ค่านี้สำหรับให้ Node อื่นๆ join เข้ามา
rke2_server_url: 192.168.172.70

# SAN (Subject Alternative Name) สำหรับใส่ใน TLS certificate ของ API Server
# ควรใส่เป็น DNS ของ Load Balancer หรือชื่อกลางของ Cluster
rke2_tls_san: "api.rke.dso.local"