# ansible-rke2-rhel9/inventory.ini

[rke2_first_control_plane]
192.168.172.89

; [rke2_other_control_planes]
; 192.168.172.72
; 192.168.172.73

; [rke2_worker]
; 192.168.172.74
; 192.168.172.75

# --- Grouping for easier targeting ---
[rke2_control_plane:children]
rke2_first_control_plane
rke2_other_control_planes

[all_nodes:children]
rke2_control_plane
rke2_worker