# ansible-rke2-rhel9/playbook.yml
- name: Prepare all nodes for RKE2 installation
  hosts: all_nodes
  roles:
    - role: common

# - name: Install first RKE2 control plane node
#   hosts: rke2_first_control_plane
#   roles:
#     - role: control_plane

# - name: Fetch the cluster join token from the first control plane
#   hosts: rke2_first_control_plane
#   tasks:
#     - name: Wait for node token to be created
#       become: true
#       ansible.builtin.wait_for:
#         path: /var/lib/rancher/rke2/server/node-token
#         timeout: 120
#     - name: Read the node token
#       become: true
#       ansible.builtin.slurp:
#         src: /var/lib/rancher/rke2/server/node-token
#       register: rke2_token_b64
#     - name: Store the token as a fact for other hosts
#       ansible.builtin.set_fact:
#         cluster_join_token: "{{ rke2_token_b64.content | b64decode | trim }}"

# - name: Install other RKE2 control plane nodes
#   hosts: rke2_other_control_planes
#   roles:
#     - role: control_plane

# - name: Install RKE2 worker nodes
#   hosts: rke2_worker
#   roles:
#     - role: worker

# - name: Fetch kubeconfig file for local use
#   hosts: rke2_first_control_plane
#   tasks:
#     - name: Fetch rke2.yaml kubeconfig
#       become: true
#       ansible.builtin.fetch:
#         src: /etc/rancher/rke2/rke2.yaml
#         dest: ./kubeconfig
#         flat: yes
#     - name: Inform user about kubeconfig
#       ansible.builtin.debug:
#         msg: "Kubeconfig file has been saved to ./kubeconfig. Use it with 'export KUBECONFIG=$(pwd)/kubeconfig'"
#       run_once: true