- name: ControlPlane | Install RKE2 server
  become: true
  ansible.builtin.shell: "curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -"
  args:
    creates: /usr/local/bin/rke2

- name: ControlPlane | Create RKE2 config directory
  become: true
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: ControlPlane | Template RKE2 config file
  become: true
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: '0644'
  notify: "Restart rke2-server"

- name: ControlPlane | Enable and start rke2-server service
  become: true
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started
    enabled: true