- name: Common | Set SELinux to permissive mode
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Common | Disable and stop firewalld
  become: true
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true # Ignore if firewalld is not installed

- name: Common | Disable swap
  become: true
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: true

- name: Common | Remove swap from /etc/fstab
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent

- name: Common | Install required packages
  become: true
  ansible.builtin.dnf:
    name:
      - curl
      - nfs-utils
    state: present